export const REFRESH_RATES = "REFRESH_RATES";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const BUY_CURRENCY = "BUY_CURRENCY";
export const SELL_CURRENCY = "SELL_CURRENCY";
export const LOG_TRANSACTION = "LOG_TRANSACTION";